
var supplyABI = [
{ constant: true,
    inputs: [],
    name: 'getBalanceEmbassy',
    outputs: [ [Object] ],
    payable: false,
    type: 'function' },
  { constant: false,
    inputs: [ [Object] ],
    name: 'withdrawFundsCitizen',
    outputs: [ [Object] ],
    payable: false,
    type: 'function' },
  { constant: false,
    inputs: [ [Object] ],
    name: 'checkEmbassy',
    outputs: [ [Object] ],
    payable: false,
    type: 'function' },
  { constant: false,
    inputs: [],
    name: 'addFunds',
    outputs: [],
    payable: true,
    type: 'function' },
  { constant: false,
    inputs: [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    name: 'checkPassport',
    outputs: [ [Object] ],
    payable: false,
    type: 'function' },
  { constant: false,
    inputs: [ [Object], [Object] ],
    name: 'addEmbassy',
    outputs: [],
    payable: false,
    type: 'function' },
  { constant: true,
    inputs: [],
    name: 'getBalanceCitizen',
    outputs: [ [Object] ],
    payable: false,
    type: 'function' },
  { constant: false,
    inputs: [ [Object] ],
    name: 'withdrawFundsEmbassy',
    outputs: [ [Object] ],
    payable: false,
    type: 'function' },
  { constant: false,
    inputs:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    name: 'createPassport',
    outputs: [],
    payable: false,
    type: 'function' },
  { inputs: [ [Object] ], payable: false, type: 'constructor' },
  { payable: true, type: 'fallback' }
]

export {supplyABI};